name: anyrouter
on:
  schedule:
    - cron: '0 8 * * *'
      timezone: 'Asia/Shanghai'
  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: anyrouter
      continue-on-error: true
      timeout-minutes: 2
      env:
        COOKIES: "MTc5MTEzMTQ3NHxEWDhFQVFMX2dBQUJFQUVRQUFEX3dfLUFBQVlHYzNSeWFXNW5EQWNBQldkeWIzVndCbk4wY21sdVp3d0pBQWRrWldaaGRXeDBCbk4wY21sdVp3d05BQXR2WVhWMGFGOXpkR0YwWlFaemRISnBibWNNRGdBTU1XdFpOR0ZqVFhwTVNsZG5Cbk4wY21sdVp3d0VBQUpwWkFOcGJuUUVCQUQtUjNZR2MzUnlhVzVuREFvQUNIVnpaWEp1WVcxbEJuTjBjbWx1Wnd3TkFBdG5hWFJvZFdKZk9URTBOd1p6ZEhKcGJtY01CZ0FFY205c1pRTnBiblFFQWdBQ0JuTjBjbWx1Wnd3SUFBWnpkR0YwZFhNRGFXNTBCQUlBQWc9PXwH7reV-ikl_Sk7wJwRfcfU_d4WLrjLxgrUS0dTGV-x_A=="
        TG_BOT_TOKEN: "xxxxxx"
        TG_CHAT_ID: "xxxxx"
      run: |
        node anyrouter.js
