name: anyrouter
on:
  schedule:
    - cron: '0 8 * * *'
      timezone: 'Asia/Shanghai'
  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: anyrouter
      continue-on-error: true
      timeout-minutes: 2
      env:
        COOKIES: "MTc4NTkzNjg1NHxEWDhFQVFMX2dBQUJFQUVRQUFEX3dfLUFBQVlHYzNSeWFXNW5EQTBBQzI5aGRYUm9YM04wWVhSbEJuTjBjbWx1Wnd3T0FBeHpURmxyVXpOcE5tRk5OelFHYzNSeWFXNW5EQVFBQW1sa0EybHVkQVFFQVA1SGRnWnpkSEpwYm1jTUNnQUlkWE5sY201aGJXVUdjM1J5YVc1bkRBMEFDMmRwZEdoMVlsODVNVFEzQm5OMGNtbHVad3dHQUFSeWIyeGxBMmx1ZEFRQ0FBSUdjM1J5YVc1bkRBZ0FCbk4wWVhSMWN3TnBiblFFQWdBQ0JuTjBjbWx1Wnd3SEFBVm5jbTkxY0FaemRISnBibWNNQ1FBSFpHVm1ZWFZzZEE9PXzqhxM-lAcE8pzOVVgR98FZ8kwcUwlxVseGx_GFBCnSGg=="
        TG_BOT_TOKEN: "xxxxxx"
        TG_CHAT_ID: "xxxxx"
      run: |
        node anyrouter.js
