name: anyrouter
on:
  schedule:
    - cron: '0 8 * * *'
      timezone: 'Asia/Shanghai'
  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: anyrouter
      continue-on-error: true
      timeout-minutes: 2
      env:
        COOKIES: "MTc4MTA2MjgyOHxEWDhFQVFMX2dBQUJFQUVRQUFEXzVQLUFBQWNHYzNSeWFXNW5EQVFBQW1sa0EybHVkQVFGQVAwRmxxQUdjM1J5YVc1bkRBb0FDSFZ6WlhKdVlXMWxCbk4wY21sdVp3d1FBQTVzYVc1MWVHUnZYekU0TXpFeU1BWnpkSEpwYm1jTUJnQUVjbTlzWlFOcGJuUUVBZ0FDQm5OMGNtbHVad3dJQUFaemRHRjBkWE1EYVc1MEJBSUFBZ1p6ZEhKcGJtY01Cd0FGWjNKdmRYQUdjM1J5YVc1bkRBa0FCMlJsWm1GMWJIUUdjM1J5YVc1bkRBVUFBMkZtWmdaemRISnBibWNNQmdBRVJHZGhkd1p6ZEhKcGJtY01EUUFMYjJGMWRHaGZjM1JoZEdVR2MzUnlhVzVuREE0QURFdEthbGsxZG1GRWRUTldjdz09fJrzjqLlC2-yMjyFga3dScXugINg1cm2K4UW_c7zeGbg"
        TG_BOT_TOKEN: "xxxxxx"
        TG_CHAT_ID: "xxxxx"
      run: |
        node anyrouter.js
